version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X github.com/tjhop/ns1_exporter/internal/version.BuildDate={{ .CommitDate }}
      - -X github.com/tjhop/ns1_exporter/internal/version.Version={{ .Version }}
      - -X github.com/tjhop/ns1_exporter/internal/version.Commit={{ .Commit }}
    binary: ns1_exporter
    main: './cmd/ns1_exporter'
gomod:
  proxy: true
  mod: mod
dockers_v2:
  - images:
      - "ghcr.io/tjhop/{{.ProjectName}}"
    tags:
      - "{{.Version}}"
      - "v{{.Version}}"
      - "latest"
    labels:
      "org.opencontainers.image.description": "NS1 Prometheus Exporter and HTTP SD Provider"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.title": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
      "org.opencontainers.image.licenses": "Apache-2.0"
    platforms:
      - linux/amd64
      - linux/arm64
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"
nfpms:
  - package_name: 'ns1_exporter'
    homepage: 'https://github.com/tjhop/ns1_exporter'
    maintainer: 'TJ Hoplock <t.hoplock@gmail.com>'
    description: 'NS1 Prometheus Exporter and HTTP SD Provider'
    formats:
      - apk
      - deb
      - rpm
      - archlinux
    bindir: /usr/bin
    contents:
      - src: ./README.md
        dst: /usr/share/doc/tjhop/ns1_exporter/README.md
      - src: ./packaging/systemd/ns1_exporter.service
        dst: /lib/systemd/system/ns1_exporter.service
        type: config
        file_info:
          mode: 0644
          owner: root
          group: root
universal_binaries:
  - replace: true
changelog:
  sort: asc
  filters:
    exclude:
      - '^Merge pull request'
      - '^ci(?:\(\w+\))?\!?:'
      - '^docs(?:\(\w+\))?\!?:'
      - '^test(?:\(\w+\))?\!?:'
      - '^style(?:\(\w+\))?\!?:'
  groups:
    - title: "New Features And Changes"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Other Changes"
      order: 999
